### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by nickverschuren** [skrollme/homebridge-people-x#4]
I'm not able to get a connection. I have a pi3b+ that's connected to a router by lan and that router is connected to my modem by lan. Ive looked everywhere, but I'm not sure how to forward my ports to get a proper connection. Also, which IP address should I use on the locative app. Sorry for the noob questions...

**Comment by skrollme** [comment]
Hello @nickverschuren ,
I can not give you some advices concerning the Locative app, because I do not use it by myself. This functionality was copied when I forked this plugin from the original one (https://github.com/PeteLawrence/homebridge-people). Maybe you find some help there for this problem.
 I only use the local ping-functionality.

**Comment by nickverschuren** [comment]
Can you give me advice on what ip i should send my url through? Is it my public address of my modem? And should i forward a port to my pi then?

Op 27 mrt. 2020 om 14:55 heeft Sebastian K <notifications@github.com> het volgende geschreven:

﻿

Hello @nickverschuren<https://github.com/nickverschuren> ,
I can not give you some advices concerning the Locative app, because I do not use it by myself. This functionality was copied when I forked this plugin from the original one (https://github.com/PeteLawrence/homebridge-people). Maybe you find some help there for this problem.
I only use the local ping-functionality.
